apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-h
  labels:
    app: bookstore-h
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bookstore-h
      tier: backend
  template:
    metadata:
      labels:
        app: bookstore-h
        tier: backend
    spec:
      containers:
      - name: bookstore-h
        image: ghcr.io/phyze/k8s/bookstore
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
      priorityClassName: high
