apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-m
  labels:
    app: bookstore-m
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bookstore-m
      tier: backend
  template:
    metadata:
      labels:
        app: bookstore-m
        tier: backend
    spec:
      containers:
      - name: bookstore-m
        image: ghcr.io/phyze/k8s/bookstore
        resources:
          limits:
            memory: "20Mi"
            cpu: "80m"
        ports:
        - containerPort: 8080
      priorityClassName: medium
