apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    name: busybox
spec:
  containers:
  - name: busybox
    image: alpine
    command: 
    - sleep 
    - "3600"
    resources:
      limits:
        memory: "30Mi"
        cpu: "190m"
