apiVersion: apps/v1
kind: Deployment
metadata:
  name: readlive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readlive
  template:
    metadata:
      labels:
        app: readlive
    spec:
      containers:
      - name: readlive
        image: ghcr.io/phyze/k8s/readlive
        resources:
          limits:
            memory: "50Mi"
            cpu: "50m"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz-liveness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
          failureThreshold: 1
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /healthz-readiness
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 3
          failureThreshold: 1
          successThreshold: 1