apiVersion: v1
kind: Pod
metadata:
  name: secret
  labels:
    name: secret
spec:
  containers:
  - name: secret
    image: ghcr.io/phyze/k8s/readlive
    resources:
      limits:
        memory: "50Mi"
        cpu: "10mi"
    ports:
      - containerPort: 8080
    env:
      - name: mysecret
        valueFrom:
          secretKeyRef:
            key: PASSWORD
