apiVersion: v1
kind: Pod
metadata:
  name: secret
  labels:
    name: secret
spec:
  containers:
  - name: secret
    image: ghcr.io/phyze/k8s/readlive
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 50Mi
    ports:
      - containerPort: 8080
    env:
      - name: mysecret
        valueFrom:
          secretKeyRef:
            key: PASSWORD
            name: mysecret
    volumeMounts:
      - mountPath: /etc/mysecretvolume
        name: mysecretvolume
        readOnly: true
  volumes:
    - name:  mysecretvolume
      secret:
        secretName: mysecret
        optional: false