apiVersion: v1
kind: Pod
metadata:
  name: private
  labels:
    name: private
spec:
  imagePullSecrets:
    - name: k8scourse
  containers:
  - name: private
    image: ghcr.io/phyze/k8s/private
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 50Mi
    ports:
      - containerPort: 8080
  