apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-l
  labels:
    app: bookstore-l
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bookstore-l
      tier: backend
  template:
    metadata:
      labels:
        app: bookstore-l
        tier: backend
    spec:
      containers:
      - name: bookstore-l
        image: ghcr.io/phyze/k8s/bookstore
        resources:
          limits:
            memory: "30Mi"
            cpu: "20m"
        ports:
        - containerPort: 8080
      priorityClassName: low
