apiVersion: v1
kind: Pod
metadata:
  name: low-priority
spec:
  containers:
  - name: low-priority
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 1;done"]
    resources:
      requests:
        cpu: 1m
        memory: 5m
      limits:
        cpu: 30m
        memory: 40Mi
  priorityClassName: low