apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  labels:
    app: nginx
data:

  MyKey: nginx

  default.conf: |
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;
        location / {
            root   /usr/share/nginx/html;
            index  index.html;
        }
    }

  index.html: |
    <h1>Hello this is configmap</h1>
