apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: gcr.io/google_samples/gb-frontend:v1